"""Add workshop submission and vote models

Revision ID: ab45454b2f9d
Revises: d1732d4b9368
Create Date: 2026-03-17 11:06:12.137336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab45454b2f9d'
down_revision = 'd1732d4b9368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=200), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workshop_submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workshop_submission_created_at'), ['created_at'], unique=False)

    op.create_table('workshop_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['workshop_submission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'voter_id', name='uq_vote_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshop_vote')
    with op.batch_alter_table('workshop_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workshop_submission_created_at'))

    op.drop_table('workshop_submission')
    # ### end Alembic commands ###
